### ISSUE TITLE
Countdown will countup instead after reaching 0 seconds

### ISSUE THREAD

**Issue by ghost** [mckamey/countdown.js#10]
After the countdown finishes, it counts up instead of showing my desired text... have I done something wrong?

`countdown.setLabels(
    ' millisecond|s|m|hr|d|w| M| Y| decade| century| millennium',
    ' millisecond|s|m|hr|d|w| M| Y| decade| century| millennium',
    '',
    '',
    'My desired end text');
`

`$scope.countdownTimer = countdown( dateObj,null,
                        countdown.DAYS |
                        countdown.HOURS |
                        countdown.MINUTES |
                        countdown.SECONDS).toString();
`

**Comment by mckamey** [comment]
That's by design. It isn't an "end text" but rather what it shows when time is zero.

There are many use cases where counting up is actually what you want rather than down. For example, exactly calculating someone's age, or a countdown to an event that then becomes time since that event.

If you want to know when it has flipped check the sign on `timespan.value`. It will get smaller and smaller and then become negative. This means your event has passed. This is useful for changing the surrounding text from a "time until" to "time since" message. You will obviously need to look at the result before you call `.toString()` on that object.
