### ISSUE TITLE
Not display the countdown on my iPad

### ISSUE THREAD

**Issue by phantanvietpk** [mckamey/countdown.js#20]
Hi, 
I have used it, but it does not display the countdown on my iPad. 
It is the issues? 
Thank you

**Comment by mckamey** [comment]
You'll need a lot more detail to get help. Does the demo work? Do the unit tests work? Is this in Safari? What version of iOS are you running?

http://countdownjs.org/demo.html
http://countdownjs.org/test/unit.html

**Comment by phantanvietpk** [comment]
Yes,
My demo work: http://24hstore-new.cnv.vn/. Is this in Safari IOS 10.3.2
Thank you

**Comment by mckamey** [comment]
Not *your* demo, but *my* demo. Do both of these links work?

http://countdownjs.org/demo.html
http://countdownjs.org/test/unit.html

**Comment by Dervisevic** [comment]
Not sure how his is configured but i have a similar issue  where the same code produces different result depending on browser:

Code:
```
import countdown from 'countdown';
var cd = countdown(new Date('2017-12-12 05:00:00'), null, countdown.DAYS | countdown.HOURS | countdown.MINUTES | countdown.SECONDS);
```
Below is the what cd is in different browsers:

Safari 11.0.1 on OS X
```
days: NaN
end: Tue Nov 21 2017 12:36:05 GMT+0100 (CET)
hours: NaN
milliseconds: NaN
minutes: NaN
seconds: NaN
start: Invalid Date
units: 30
value: NaN
```

Chrome 62.0.3202.94 on OS X
```
days: 20
end: Tue Nov 21 2017 12:37:01 GMT+0100 (CET) {}
hours: 16
minutes: 22
seconds: 58
start: Tue Dec 12 2017 05:00:00 GMT+0100 (CET) {}
units: 30
value: -1786978337
```

**Comment by mckamey** [comment]
new Date('2017-12-12 05:00:00') is not supported by all browsers. Either specify milliseconds since epoch for a specific instance in time or specify each as a separate integer (remember that months are zero based, and leading zeros make it octal so drop them):
new Date(2017, 11, 12, 5, 0, 0)

**Comment by Dervisevic** [comment]
Yeah, shortly after I realized that safari had issues with this format and I deleted the comment.


Cheers for the clarification!


On Tue, Nov 21, 2017 at 5:42pm, Stephen McKamey < notifications@github.com [notifications@github.com] > wrote:
new Date('2017-12-12 05:00:00') is not supported by all browsers. Either specify milliseconds since epoch for a specific instance in time or specify each as a separate integer (remember that months are zero based, and leading zeros make it octal so drop them):
new Date(2017, 11, 12, 5, 0, 0)
