### ISSUE TITLE
Display units based on config, not value

### ISSUE THREAD

**Issue by Jelle-S** [mckamey/countdown.js#41]
When a value is 0, the formatList function does not add it to the list, even though it is configured to be displayed in the timpstamp units property. This means that the countdown looks something like this:
```
2 hours
19 minutes
1 second
```
and a second later looks like this:
```
2 hours
19 minutes
```
and then 19 minutes later:
```
2 hours
1 second
```
While, IMHO it should be:
```
2 hours
19 minutes
0 seconds
```
and 
```
2 hours
0 minutes
1 second
```
respectively

**Comment by mckamey** [comment]
That is by design. When _humans_ say how long something is, _no one_ says "...and zero seconds" or anything like that. When someone asks my age, I don't start by saying "Zero millennia, zero centuries, ...".

If you want to do that, go ahead and create a custom render function and you can render the string however you want. There are plenty of examples on doing that.
