### ISSUE TITLE
Problem with countdown

### ISSUE THREAD

**Issue by sektor2704** [mckamey/countdown.js#8]
Hi
I want to start the timer by pressing the button. I wrote this function

``` html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">
<html>
<head>
    <script type="text/javascript" src="countdownjs/countdown.min.js"></script>
    <title>countdownjs</title>
</head>

<body>

<table width="90%" cellspacing="1" cellpadding="6" align="center" border="1">
<tr>
    <td>
        <div id="counter"></div>
    </td>
</tr>
<tr>
    <td>
        <input type="text" id="timespent" value="1437670253">
        <input type="button" value="Start" onclick="start_countdown();">

        <script type="text/javascript">
        <!--
            function start_countdown() {
                var time = document.getElementById('timespent').value;
                countdown(
                    new Date(time * 1000),
                    function(ts) {
                        document.getElementById('counter').innerHTML = ts.toHTML();
                    }, countdown.DEFAULTS
                );
            }
        // -->
        </script>
    </td>
</tr>
</table>

</body>

</html>
```

When you first run it works fine, but if you change the time and again press the "Start" then the timer begins to fail. What I did wrong?

**Comment by mckamey** [comment]
There are a ton of stylistic things (HTML 4 vs. HTML 5, type of script is "text/javascript" rather than "application/javascript", unnecessary comment around the script block, value of an input is text but using implicit type coercion to treat as a number without checking input, etc.) but I think the issue you are noticing is that every time the button is pressed you actually kick off a new countdown timer without cancelling the previous timer.

So it isn't really "failing" so much as being updated by interleaving timers. If you initiate a timer like this (meaning with a callback so that it continues to run) then you either need to store the result somewhere so that you can call `clearInterval(timerId)` before you create a new timer (probably your best bet), or add a second parameter to your callback to get the `timerId` and cancel it within the callback itself.
