### ISSUE TITLE
Is it possible .toHTML("tag","class")?

### ISSUE THREAD

**Issue by Ajaxsoap** [mckamey/countdown.js#9]
Hi,

Thank you for this awesome library!

I am wondering if possible to format the result like:

`
countdown(start,end,units,max,digits).toHTML("button", "classname") ?
`

button.btn btn-warning

then if the start `now <= countdown.MONTHS .toHTML("button","btn btn-danger")`

or I should write a custom function for it?

Thanks,

**Comment by mckamey** [comment]
Short answer, "No". I'm not exactly sure what you are trying to do, so I'll just explain what the library does so you can figure out where it fits into your needs.

I don't think `toHTML()` does what you think it does. All `toHTML()` does is return the result as a string with HTML around each unit. This library doesn't really deal with UI. That method simply makes it easier to inject a tiny bit of markup around the parts.

Also `countdown.MONTHS` is a constant which is used for the `units` argument not something you compare against.

So a variation on the `toHTML()` example from [the readme](https://github.com/mckamey/countdownjs/blob/master/README.md):

``` javascript
// your example code
var timespan = countdown(start, end, units, max, digits);

// produces something like "<em>1 month</em>, <em>12 hours</em> and <em>17 minutes</em>"
var message = timespan.toHTML("em");
```

You can do whatever you want with that HTML like jam it into a button I guess. To detect if the timer has passed the fixed date, you will want to check `timespan.value` which is the exact delta (in ms) between `start` and `end`. If the sign is negative then `start` now represents a date after `end`. (As a reminder, if you pass `null` into either one, it will be populated with `Date.now()`. Passing `null` into both is possible but silly because it would always return zero.)

So adding that to the earlier example:

``` javascript
// your example code
var timespan = countdown(start, end, units, max, digits);

// produces something like "<em>1 month</em>, <em>12 hours</em> and <em>17 minutes</em>"
var message = timespan.toHTML("em");

// this might need to be > 0, depending on what you use for start & end
if (timespan.value < 0) {
   // do something with 'btn danger'
} else {
   // do something with 'btn normal'
}
```

What you pass into `start` and `end` will determine the sign of `timespan.value`. So if you are consistently passing them in a particular order then all you do is watch for the sign of `timespan.value` to flip to know if the moving date has passed the fixed date.

**Comment by Ajaxsoap** [comment]
Thank you for the quick answer @mckamey! 
Yeah, the UI part is what I am trying to manipulate depends on the timespan, the scenario is exactly the example you provided above, the button will change its color if the timespan has reached a certain time.

```
var message = timespan.toHTML("buttton");

// this might need to be > 0, depending on what you use for start & end
if (timespan.value <= result ) {
   btn-danger
} else {
   btn-primary
}
```

Now I know what to do! :)

Thanks Again @mckamey!

Cheers!

**Comment by mckamey** [comment]
Remember `value` is the delta not absolute. So:

```
var message = timespan.toHTML("buttton");

// this might need to be > 0, depending on what you use for start & end
if (timespan.value < 0) { // note result
   btn-danger
} else {
   btn-primary
}
```

**Comment by Ajaxsoap** [comment]
Ok, here's my code:

```
var dateNow = null;
var monthLeft = countdown(dateNow, dateMaturity, countdown.MONTHS | countdown.DAYS, 2).toHTML("button");
```

If monthLeft reached one month, assuming the value has reached "1 month" which is the delta value right? How do I represent the absolute as a delta value? or the other way around?

**Comment by mckamey** [comment]
As I've been saying I'm certain that you don't get what `toHTML` is doing. Don't call it yet. Look at the object returned that has `toHTML` on it (the TimeSpan object).

It has all the fields you need on it. `value` is the delta with the sign. `months` has how many months there are. You will need to try running it.

**Comment by Ajaxsoap** [comment]
I am sorry about that, I get what toHTML is doing and it's doing a great job on my app.

It's just I'm only confused on the delta and absolute term as I am seldom encountered this terms even if I've deal with it everyday haha. 

Thanks again @mckamey!

**Comment by mckamey** [comment]
By delta/difference/relative (`timespan.value`) I mean the milliseconds between `start` and `end`. And by absolute I mean the `start` and `end` dates. So both dates are (under the hood) simply an integer of the number of milliseconds since midnight Jan 1, 1970 UTC.

``` javascript
value = end - start;
```

All three are added to the `timespan` object as fields.

If you want to know when there is less than a month left, you probably need to check `timespan.value > 0 && timespan.months < 1` since a month **after** the value will be negative and month will be 1 again.

The reason I don't think you get what `toHTML` is for is that 1) you are calling it too early (before you've checked the values on timespan), and 2) if you pass in 'button' then you will get back text with a bunch of buttons in there. Perhaps that's what you want but it doesn't sound right to me.

**Comment by Ajaxsoap** [comment]
Thanks @mckamey for the insights and effort :+1:
